import { DreamEntry, UserProfile, DreamHealthIndex } from '@/types'

// Mock 사용자 프로필
export const mockUserProfile: UserProfile = {
  id: 'user-1',
  name: '꿈꾸는 사람',
  email: 'dreamer@example.com',
  createdAt: new Date('2024-01-01'),
  dreamCount: 0,
  healthIndex: {
    stressLevel: 35,
    anxietyLevel: 40,
    emotionalResilience: 75,
    relationshipStress: 25,
    sleepQuality: 70,
    nightmareRatio: 0.2,
    lastUpdated: new Date(),
  },
}

// Mock 꿈 데이터
export const mockDreams: DreamEntry[] = [
  {
    id: '1',
    userId: 'user-1',
    title: '하늘을 나는 꿈',
    content:
      '갑자기 중력이 사라지면서 하늘로 떠올랐다. 구름 위를 걸으며 세상을 내려다보니 모든 것이 평화로워 보였다. 새들과 함께 날아다니며 자유를 만끽했다.',
    recordedAt: new Date('2024-02-10'),
    createdAt: new Date('2024-02-10'),
    inputMethod: 'text',
    style: 'healing',
    scenes: [
      {
        id: 's1',
        sceneNumber: 1,
        description: '하늘로 떠오르는 장면',
        characters: ['나'],
        emotion: 'surprise',
        backgroundKeywords: ['하늘', '구름', '햇빛'],
        narration: '갑자기 몸이 가벼워지면서 하늘로 떠올랐다.',
      },
      {
        id: 's2',
        sceneNumber: 2,
        description: '구름 위를 걷는 장면',
        characters: ['나', '새들'],
        emotion: 'joy',
        backgroundKeywords: ['구름', '하늘', '태양'],
        narration: '구름이 솜사탕처럼 부드러웠다.',
        dialogue: [{ character: '나', text: '이게 꿈이라니 믿을 수 없어...' }],
      },
      {
        id: 's3',
        sceneNumber: 3,
        description: '자유롭게 날아다니는 장면',
        characters: ['나'],
        emotion: 'peace',
        backgroundKeywords: ['하늘', '바람', '자유'],
        narration: '완벽한 자유를 느꼈다.',
      },
    ],
    analysis: {
      emotions: {
        joy: 60,
        anxiety: 5,
        anger: 0,
        sadness: 0,
        surprise: 20,
        peace: 80,
      },
      tensionLevel: 10,
      controlLevel: 85,
      isNightmare: false,
      repeatingSymbols: ['하늘', '자유', '비행'],
      relationshipPatterns: [],
      hasResolution: true,
    },
    webtoonUrl: '/webtoons/1',
    tags: ['비행', '자유', '평화'],
    isFavorite: true,
  },
  {
    id: '2',
    userId: 'user-1',
    title: '시험을 보는 악몽',
    content:
      '시험장에 앉아있는데 아무것도 기억나지 않았다. 시간은 점점 흘러가고 주변 사람들은 모두 열심히 쓰고 있었다. 패닉 상태가 되었지만, 갑자기 답이 떠올랐다.',
    recordedAt: new Date('2024-02-08'),
    createdAt: new Date('2024-02-08'),
    inputMethod: 'text',
    style: 'school',
    scenes: [
      {
        id: 's1',
        sceneNumber: 1,
        description: '시험장에 앉아있는 장면',
        characters: ['나', '학생들'],
        emotion: 'anxiety',
        backgroundKeywords: ['교실', '책상', '시험지'],
        narration: '백지 상태의 시험지가 나를 압박했다.',
      },
      {
        id: 's2',
        sceneNumber: 2,
        description: '패닉 상태가 되는 장면',
        characters: ['나'],
        emotion: 'anxiety',
        backgroundKeywords: ['시계', '땀', '긴장'],
        narration: '시계 소리가 점점 크게 들렸다.',
        dialogue: [{ character: '나', text: '아무것도 기억이 안 나...' }],
      },
      {
        id: 's3',
        sceneNumber: 3,
        description: '답이 떠오르는 장면',
        characters: ['나'],
        emotion: 'joy',
        backgroundKeywords: ['빛', '깨달음'],
        narration: '갑자기 모든 답이 선명하게 보였다.',
        dialogue: [{ character: '나', text: '이제 알겠어!' }],
      },
    ],
    analysis: {
      emotions: {
        joy: 20,
        anxiety: 70,
        anger: 10,
        sadness: 15,
        surprise: 30,
        peace: 5,
      },
      tensionLevel: 80,
      controlLevel: 30,
      isNightmare: true,
      repeatingSymbols: ['시험', '시간', '압박'],
      relationshipPatterns: ['경쟁', '비교'],
      hasResolution: true,
    },
    webtoonUrl: '/webtoons/2',
    tags: ['시험', '불안', '학교'],
    isFavorite: false,
  },
  {
    id: '3',
    userId: 'user-1',
    title: '바닷속 모험',
    content:
      '숨을 쉴 수 있는 바닷속에 있었다. 형형색색의 물고기들과 산호초가 아름다웠다. 인어를 만나 함께 해저 궁전을 탐험했다.',
    recordedAt: new Date('2024-02-05'),
    createdAt: new Date('2024-02-05'),
    inputMethod: 'voice',
    style: 'dark-fantasy',
    scenes: [
      {
        id: 's1',
        sceneNumber: 1,
        description: '바닷속에 들어가는 장면',
        characters: ['나'],
        emotion: 'surprise',
        backgroundKeywords: ['바다', '물', '빛'],
        narration: '물속에서도 숨을 쉴 수 있다는 것을 깨달았다.',
      },
      {
        id: 's2',
        sceneNumber: 2,
        description: '인어를 만나는 장면',
        characters: ['나', '인어'],
        emotion: 'joy',
        backgroundKeywords: ['산호초', '물고기', '궁전'],
        dialogue: [
          { character: '인어', text: '우리 궁전에 온 걸 환영해요.' },
          { character: '나', text: '정말 아름답군요!' },
        ],
      },
      {
        id: 's3',
        sceneNumber: 3,
        description: '해저 궁전 탐험',
        characters: ['나', '인어'],
        emotion: 'peace',
        backgroundKeywords: ['궁전', '보물', '신비'],
        narration: '해저 궁전은 상상 이상으로 장엄했다.',
      },
    ],
    analysis: {
      emotions: {
        joy: 70,
        anxiety: 10,
        anger: 0,
        sadness: 5,
        surprise: 60,
        peace: 65,
      },
      tensionLevel: 20,
      controlLevel: 70,
      isNightmare: false,
      repeatingSymbols: ['물', '탐험', '신비'],
      relationshipPatterns: ['새로운 만남'],
      hasResolution: true,
    },
    webtoonUrl: '/webtoons/3',
    tags: ['바다', '모험', '인어'],
    isFavorite: true,
  },
]
